### ISSUE TITLE
Steps to install differentiable augmentation (DA) pipeline from StyleGAN2-ADA

### ISSUE THREAD

**Issue by IvanGarcia7** [boschresearch/one-shot-synthesis#2]
Hello.

I'm trying to execute one-shot-synthesis on my custom dataset so I followed the steps defined in this repo. Additionally, it's determined that it needs the differentiable augmentation (DA) pipeline from StyleGAN2-ADA but I can't see any information in the repo provided about how to install it.

**Comment by SushkoVadim** [comment]
Hi,

Some information was shared in a previous issue: https://github.com/boschresearch/one-shot-synthesis/issues/1#issuecomment-1140862976, have you already checked this discussion?
Please let me know if any step still remains unclear. 

Vadim
