### ISSUE TITLE
Where should I place the masks?

### ISSUE THREAD

**Issue by cagatayp0** [boschresearch/one-shot-synthesis#3]
Hello.

When I run train.py it says "Using the training regime *without* segmentation masks". I already have segmentation masks. Which directory must I place masks so that the model can see them.

**Comment by SushkoVadim** [comment]
Hi,

The regime using segmentation masks is not supported in the current release. We plan to release it in the following months.
The model can see the masks if they are placed under `${dataset_name}/masks` (but the code functionality is still not provided, so it needs to be implemented).

**Comment by rahup97** [comment]
Hi @SushkoVadim, has this been implemented yet? I have all the dependencies installed as per the YAML file, but only the --no-masks version runs bug free. TIA!

**Comment by SushkoVadim** [comment]
Hi,

Yes, this has been added. See commit `ba7af89e0d65871c0f5aa9660fff99a86186613c`.
The current version of code in master should contain all the nessesary code.

What is the error you see when you try to run with masks?

Vadim

**Comment by rahup97** [comment]
Hi @SushkoVadim, while running for a single image-mask pair I hit the following error right after Generator and Discriminator are intialized:

```
/home/rmpatil/multi_task_gen/labelGAN/misc-and-old/one-shot-synthesis-osmis/core/feature_augmentation.py:230: UserWarning:This overload of nonzero is deprecated:
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  idx_x1 = torch.nonzero(old_area * 1.0)[:, 0].min()

Traceback (most recent call last):
  File "train.py", line 44, in <module>
    losses["Dreal"] = losses_computer(logits["Dreal"], batch, real=True, forD=True)
  File "/home/rmpatil/multi_task_gen/labelGAN/misc-and-old/one-shot-synthesis-osmis/core/losses.py", line 73, in __call__
    losses[item] = losses.get(item, 0) + self.content_segm_loss(out_d[item][i], data, real, forD)
  File "/home/rmpatil/multi_task_gen/labelGAN/misc-and-old/one-shot-synthesis-osmis/core/losses.py", line 43, in content_segm_loss
    loss = F.cross_entropy(out_d, ground_t.long().to(out_d.device), weight=weights.to(out_d.device))
  File "/opt/conda/envs/osmis/lib/python3.8/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/envs/osmis/lib/python3.8/site-packages/torch/nn/functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: weight tensor should be defined either for all or no classes at /pytorch/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:27
```

My mask is for a binary semantic segmentation task, where the pixel labels are either white or black in color and mask is of type RGBA.

**Comment by rahup97** [comment]
Hi @SushkoVadim, so I just tried converting my mask from RGBA to "L" (or grayscale) and now the model starts to train. This is kind of odd, maybe could you mention in the readme that the masks should not have an alpha channel as I know the method accepts multi-class masks.

**Comment by SushkoVadim** [comment]
Hi, thanks for noting.
I assumed the mask format should be clear from the examples in the `datasets` folder. Indeed worth a mention in the Readme. Thanks!

Vadim
